server:
  port: 8081
  servlet:
    context-path: /learn
    session:
      cookie:
        name: BIUSID
logging:
  path: ./logs
  level:
    com.telchina.cq: debug
---
# 测试环境配置
spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  # profiles: test
  application:
    name: codein
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@10.34.69.61:1521:orcl
#    username: zhongxin
#    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.10.50.198:1521:orcl
    username: DGCACYYZT
    password: DGCACYYZT
#    开发
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://10.10.50.198:5432/bjwlc?currentSchema=business
#    username: product
#    password: product123456
#    编译
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://10.10.60.91:5432/bjwlc?currentSchema=business
#    username: postgres
#    password: postgres
    druid:
      initialSize: 5
      minIdle: 5
      maxWait: 60000
      maxActive: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.telchina.cq.mvc.vo
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    #refresh-mapper: true
  configuration:
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'